name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '18'
    - name: Build with Maven
      run: mvn clean install

